"""Render docs/analysis-report.md from the JSON the other steps wrote.

    python -m analysis.report

Deterministic: re-running on the same inputs produces the same file.
"""

import json
import logging
from pathlib import Path
from typing import Any

from analysis import config
from analysis.cli import repo_relative, setup_logging

log = logging.getLogger("report")

_PARTS = (("head", "Still start"), ("yawn", "Yawn"), ("tail", "Still end"))


def _link(repo_path: str) -> str:
    """Link from docs/ to a repo-relative file."""
    return f"[`{Path(repo_path).name}`](../{repo_path})"


def _clip_section(probe: dict[str, Any]) -> list[str]:
    lines = [
        "## Source clip", "",
        "| Clip | Size | FPS | Frames | Duration | Codec | Audio |",
        "|---|---|---|---|---|---|---|",
    ]
    for clip in probe["clips"]:
        audio = "yes (stripped)" if clip["has_audio"] else "no"
        lines.append(
            f"| `{Path(clip['path']).name}` | {clip['width']}×{clip['height']} | {clip['frame_rate']} "
            f"| {clip['frame_count']} | {clip['duration_s']:.2f} s | {clip['codec']} / {clip['pix_fmt']} | {audio} |"
        )
    return lines


def _segment_sections(segments: dict[str, Any]) -> list[str]:
    fps = segments["fps"]
    previews = segments["previews"]
    lines = [
        "## Segments", "",
        f"Normalised clip `{segments['clip']}`: {segments['frame_count']} frames at {fps:g} fps.", "",
        "| Part | Frames | Length |",
        "|---|---|---|",
    ]
    for key, label in _PARTS:
        start, end = segments["segments"][key]
        lines.append(f"| {label} | {start}–{end} | {(end - start + 1) / fps:.2f} s |")
    lines += [
        "",
        f"Yawn = smoothed motion above {segments['threshold']:.3f} (still level {segments['still_level']:.3f}).",
    ]
    if segments["overrides"]:
        detected_start, detected_end = segments["detected_yawn"]
        lines += [
            f"Boundaries corrected by hand in `analysis/config.py` (`SEGMENT_OVERRIDES`: {segments['overrides']}); "
            f"auto-detected yawn was {detected_start}–{detected_end}.",
        ]
    lines += [
        f"Motion plot: {_link(previews['motion'])}. Frames with segment colours "
        f"(green start, red yawn, blue end): {_link(previews['contact_sheet'])}.",
        "",
        "## Natural drift in the still parts", "",
        "Mean absolute difference (grey levels, 0–255) between frames `gap` apart, on blurred "
        f"{config.DESCRIPTOR_LONG_SIDE}px-tall descriptors. This is the yardstick for seam costs.", "",
        "| Gap (frames) | Seconds | Mean change |",
        "|---|---|---|",
    ]
    for gap, value in segments["natural_drift"].items():
        lines.append(f"| {gap} | {int(gap) / fps:.2f} | {value:.3f} |")

    reference = segments["natural_drift"].get(str(config.DRIFT_REFERENCE_GAP))
    lines += [
        "",
        "## Best end → start cuts", "",
        "Windowed cost (brief 2c) of showing still-end frame *i*, then still-start frame *j*. "
        "Idle looping and entering the yawn both use this jump.", "",
        f"| Cut | Cost | × drift over {config.DRIFT_REFERENCE_GAP} frames |",
        "|---|---|---|",
    ]
    for cut in segments["best_end_to_start_cuts"]:
        ratio = f"{cut['cost'] / reference:.1f}×" if reference else "n/a"
        lines.append(f"| {cut['from_frame']} → {cut['to_frame']} | {cut['cost']:.3f} | {ratio} |")
    if "seam_difference" in previews:
        lines += [
            "",
            f"Best cut vs natural drift, amplified ×8: {_link(previews['seam_difference'])}.",
        ]
    return lines


def render(probe: dict[str, Any], segments: dict[str, Any] | None) -> str:
    lines = [
        "# Analysis report", "",
        "_Generated by `python -m analysis.report` from `build/probe.json` and `build/segments.json`. "
        "Re-run the pipeline rather than editing by hand._", "",
    ]
    lines += _clip_section(probe)
    flags = probe["issues"] + (segments["issues"] if segments else [])
    lines += ["", "## Flags", ""] + ([f"- {flag}" for flag in flags] or ["- none"])
    lines += [""]
    if segments is None:
        lines += ["_Segmentation hasn't run or failed; see the pipeline log._"]
    else:
        lines += _segment_sections(segments)
    return "\n".join(lines) + "\n"


def _load(path: Path) -> dict[str, Any] | None:
    return json.loads(path.read_text()) if path.is_file() else None


def run(
    probe_json: Path = config.PROBE_JSON,
    segments_json: Path = config.SEGMENTS_JSON,
    out: Path = config.REPORT_MD,
) -> Path:
    probe = _load(probe_json)
    if probe is None:
        raise FileNotFoundError(f"{repo_relative(probe_json)} missing; run analysis.probe first")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render(probe, _load(segments_json)))
    log.info("wrote %s", repo_relative(out))
    return out


def main() -> None:
    setup_logging()
    run()


if __name__ == "__main__":
    main()
